FROM oven/bun:1
WORKDIR /app
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
RUN bun install
COPY ./turbo.json ./turbo.json
RUN bun run db:generate
COPY ./apps/backend ./apps/backend

CMD [ "bun","run","start:be" ]