FROM oven/bun:1
WORKDIR /app
ARG DATABASE_URL
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
RUN bun install
COPY ./turbo.json ./turbo.json
RUN bun run db:generate
COPY ./apps/web ./apps/web
RUN DATABASE_URL=${DATABASE_URL} bun run build

CMD [ "bun","run","start:fe" ]