name: todo-app-frontend-deployment
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v2
              with:
                fetch-depth: '0'
            - name: docker login
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            - name: docker build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./docker/Dockerfile.frontend
                build-args: 
                    -DATABASE_URL=${{secrets.DATABASE_URL}}
                push: true
                tags: vishw76/todo-app-websocket:${{github.sha}}

 